"use client";
import { useEffect, useMemo, useState } from "react";

type Home={id:string;address1:string;city:string;state:string;property_code?:string|null};
type Tx={id:string;tx_date:string;vendor_name?:string|null;description?:string|null;account_name?:string|null;amount_cents:number;flow_type:"income"|"expense";allocation_status:"matched"|"review"|"overhead";match_confidence:number;homes?:Home|null;property_id?:string|null};
const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(c/100);

function parseCsv(text:string){
  const rows:string[][]=[]; let row:string[]=[]; let cell=""; let q=false;
  for(let i=0;i<text.length;i++){const ch=text[i]; if(ch==='"'){if(q&&text[i+1]==='"'){cell+='"';i++;}else q=!q;} else if(ch===','&&!q){row.push(cell);cell="";} else if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&text[i+1]==='\n')i++; row.push(cell); if(row.some(x=>x.trim()!==""))rows.push(row); row=[];cell="";} else cell+=ch;}
  if(cell||row.length){row.push(cell);rows.push(row);} const headers=(rows.shift()||[]).map(x=>x.trim());
  return {headers,rows:rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??""])))};
}

export default function Financials(){
  const [mode,setMode]=useState("checking"); const [homes,setHomes]=useState<Home[]>([]); const [tx,setTx]=useState<Tx[]>([]); const [filter,setFilter]=useState<"all"|"review"|"matched"|"overhead">("all");
  const [selected,setSelected]=useState<string[]>([]); const [showImport,setShowImport]=useState(false); const [fileName,setFileName]=useState(""); const [headers,setHeaders]=useState<string[]>([]); const [rows,setRows]=useState<Record<string,string>[]>([]); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState("");
  const [mapping,setMapping]=useState<any>({date:"",description:"",vendor:"",amount:"",debit:"",credit:"",account:"",qbClass:"",qbLocation:"",customerProject:"",memo:"",positiveMeans:"expense"});
  async function load(){const r=await fetch("/api/financial/bootstrap"); const b=await r.json(); if(r.status===401){setMode("auth");return;} if(!r.ok){setMode("error");setMsg(b.error||"Could not load financials");return;} setMode(b.mode);setHomes(b.homes||[]);setTx(b.transactions||[]);}
  useEffect(()=>{load()},[]);
  const visible=useMemo(()=>filter==="all"?tx:tx.filter(t=>t.allocation_status===filter),[tx,filter]);
  const revenue=tx.filter(t=>t.flow_type==="income").reduce((s,t)=>s+t.amount_cents,0); const expenses=tx.filter(t=>t.flow_type==="expense").reduce((s,t)=>s+t.amount_cents,0); const review=tx.filter(t=>t.allocation_status==="review").length;
  const byHome=useMemo(()=>homes.map(h=>{const rows=tx.filter(t=>t.homes?.id===h.id||t.property_id===h.id);const inc=rows.filter(t=>t.flow_type==="income").reduce((s,t)=>s+t.amount_cents,0);const exp=rows.filter(t=>t.flow_type==="expense").reduce((s,t)=>s+t.amount_cents,0);return {h,inc,exp,noi:inc-exp,review:rows.filter(t=>t.allocation_status==="review").length}}),[homes,tx]);
  async function assign(id:string,propertyId:string|null,overhead=false){if(mode!=="live"){setTx(xs=>xs.map(t=>t.id===id?{...t,allocation_status:overhead?"overhead":propertyId?"matched":"review",property_id:propertyId,homes:homes.find(h=>h.id===propertyId)||null,match_confidence:propertyId||overhead?1:0}:t));return;} const r=await fetch(`/api/financial/transactions/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(overhead?{markOverhead:true}:{propertyId})}); if(r.ok){const b=await r.json();setTx(xs=>xs.map(t=>t.id===id?b.transaction:t));}}
  async function bulk(propertyId?:string,overhead=false){if(!selected.length)return; if(mode!=="live"){for(const id of selected)await assign(id,propertyId||null,overhead);setSelected([]);return;} setBusy(true); const r=await fetch("/api/financial/bulk-review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids:selected,propertyId,markOverhead:overhead})}); setBusy(false); if(r.ok){setSelected([]);load();}}
  function chooseFile(file?:File){if(!file)return;setFileName(file.name);file.text().then(text=>{const p=parseCsv(text);setHeaders(p.headers);setRows(p.rows); const find=(...needles:string[])=>p.headers.find(h=>needles.some(n=>h.toLowerCase().includes(n)))||""; setMapping((m:any)=>({...m,date:find("date"),description:find("description","name"),vendor:find("vendor","payee"),amount:find("amount"),debit:find("debit"),credit:find("credit"),account:find("account"),qbClass:find("class"),qbLocation:find("location"),customerProject:find("customer","project"),memo:find("memo")}));});}
  async function importRows(){if(!mapping.date||(!mapping.amount&&!mapping.debit&&!mapping.credit)){setMsg("Map a date and either amount or debit/credit columns first.");return;} if(mode!=="live"){setMsg("Import mapping is ready. Connect Supabase to persist the QuickBooks export.");return;} setBusy(true);const r=await fetch("/api/financial/imports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fileName,mapping,rows})});const b=await r.json();setBusy(false);if(!r.ok){setMsg(b.error||"Import failed");return;}setMsg(`Imported ${b.total} rows: ${b.matched} auto-matched, ${b.review} need review.`);setShowImport(false);load();}
  return <main className="finShell">
    <aside className="finSide"><a className="brand finBrand" href="/"><div className="brandMark">H</div><div><strong>HomeOps</strong><span>Rental home OS</span></div></a><nav><a className="finNav" href="/">Operations</a><a className="finNav active" href="/financials">Financials</a></nav><div className="portfolio"><small>CONTROLLER VIEW</small><strong>{homes.length} doors</strong><span>{review} items need review</span><span className={`mode ${mode}`}>{mode==="live"?"● Live accounting data":mode==="demo"?"○ Demo financial data":"Backend status: "+mode}</span></div></aside>
    <section className="finContent"><header className="finHeader"><div><p className="eyebrow">FINANCIAL ONBOARDING</p><h1>Controller workspace</h1><p>Import QuickBooks data, align every transaction to a property, and review portfolio performance.</p></div><div className="headerActions">{mode==="auth"&&<a className="secondaryBtn" href="/login">Sign in</a>}<button className="primary" onClick={()=>setShowImport(true)}>Import QuickBooks export</button></div></header>
    {msg&&<div className="backendBanner">{msg}</div>}
    <div className="stats finStats"><div className="stat"><span>Portfolio revenue</span><div className="statValue good">{money(revenue)}</div><small>Imported period</small></div><div className="stat"><span>Expenses</span><div className="statValue">{money(expenses)}</div><small>Property + overhead</small></div><div className="stat"><span>Net operating result</span><div className="statValue">{money(revenue-expenses)}</div><small>Before debt service</small></div><div className="stat"><span>Needs review</span><div className="statValue warn">{review}</div><small>Unassigned / low-confidence</small></div></div>
    <div className="panel"><div className="panelHead"><div><p className="eyebrow">EXCEPTIONS</p><h2>Transaction review queue</h2></div><div className="finFilters">{(["all","review","matched","overhead"] as const).map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}</button>)}</div></div>
      {selected.length>0&&<div className="bulkBar"><strong>{selected.length} selected</strong><select defaultValue="" onChange={e=>{if(e.target.value)bulk(e.target.value,false)}}><option value="">Assign all to property…</option>{homes.map(h=><option key={h.id} value={h.id}>{h.address1}</option>)}</select><button onClick={()=>bulk(undefined,true)} disabled={busy}>Mark company overhead</button></div>}
      <div className="finTable"><div className="finTr finHead"><span></span><span>Date / vendor</span><span>Account</span><span>Amount</span><span>Property assignment</span><span>Confidence</span></div>{visible.map(t=><div className="finTr" key={t.id}><span><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,t.id]:s.filter(x=>x!==t.id))}/></span><span><strong>{t.vendor_name||t.description||"Transaction"}</strong><small>{t.tx_date} · {t.description}</small></span><span>{t.account_name||"Uncategorized"}</span><span className={t.flow_type}>{t.flow_type==="income"?"+":"−"}{money(t.amount_cents)}</span><span><select value={t.allocation_status==="overhead"?"overhead":t.homes?.id||t.property_id||""} onChange={e=>e.target.value==="overhead"?assign(t.id,null,true):assign(t.id,e.target.value||null)}><option value="">Needs review</option><option value="overhead">Company overhead</option>{homes.map(h=><option key={h.id} value={h.id}>{h.address1}</option>)}</select></span><span><b className={`confidence ${t.match_confidence>=.9?"high":t.match_confidence>.5?"medium":"low"}`}>{Math.round((t.match_confidence||0)*100)}%</b></span></div>)}</div>
    </div>
    <div className="panel"><div className="panelHead"><div><p className="eyebrow">DOOR PERFORMANCE</p><h2>Property financial snapshot</h2></div><span className="pill">Imported period</span></div><div className="portfolioTable"><div className="portfolioTr head"><span>Property</span><span>Revenue</span><span>Expenses</span><span>NOI</span><span>Review</span></div>{byHome.map(x=><div className="portfolioTr" key={x.h.id}><span><strong>{x.h.address1}</strong><small>{x.h.city}, {x.h.state}</small></span><span>{money(x.inc)}</span><span>{money(x.exp)}</span><span><strong>{money(x.noi)}</strong></span><span>{x.review||"—"}</span></div>)}</div></div>
    </section>
    {showImport&&<div className="modalShade"><div className="modal importModal"><div className="modalHead"><div><p className="eyebrow">QUICKBOOKS IMPORT</p><h2>Map your export once</h2></div><button className="closeBtn" onClick={()=>setShowImport(false)}>×</button></div><p className="summary">HomeOps does not assume properties are stored as Classes, Locations, Customers, or Projects. Map whatever your QuickBooks file uses; unmatched rows go to the controller review queue.</p><label className="dropZone">Choose QuickBooks CSV / Excel-exported CSV<input type="file" accept=".csv,text/csv" onChange={e=>chooseFile(e.target.files?.[0])}/><strong>{fileName||"Choose CSV file"}</strong><span>{rows.length?`${rows.length} transactions detected`:"Export a report from QuickBooks Online as CSV-compatible data"}</span></label>{headers.length>0&&<div className="mappingGrid">{[["date","Transaction date *"],["vendor","Vendor / payee"],["description","Description"],["amount","Amount"],["debit","Debit"],["credit","Credit"],["account","Account / category"],["qbClass","QuickBooks Class"],["qbLocation","QuickBooks Location"],["customerProject","Customer / Project"],["memo","Memo"]].map(([key,label])=><label key={key}>{label}<select value={mapping[key]||""} onChange={e=>setMapping({...mapping,[key]:e.target.value})}><option value="">Not mapped</option>{headers.map(h=><option key={h} value={h}>{h}</option>)}</select></label>)}<label>Amount sign convention<select value={mapping.positiveMeans} onChange={e=>setMapping({...mapping,positiveMeans:e.target.value})}><option value="expense">Positive = expense</option><option value="income">Positive = income</option></select></label></div>}<div className="modalActions"><button className="secondaryBtn" onClick={()=>setShowImport(false)}>Cancel</button><button className="primary" onClick={importRows} disabled={busy||!rows.length}>{busy?"Importing…":"Import & auto-match"}</button></div></div></div>}
  </main>
}
