"use client";
import { useEffect, useMemo, useState } from "react";
import BrandLockup from "@/components/brand-lockup";
import BrandIcon from "@/components/brand-icon";
import { buildPortfolioIntelligence, type IntelligenceHome as Home, type IntelligenceTransaction as Tx } from "@/lib/portfolio-intelligence";

type View="overview"|"properties"|"services"|"trends"|"review";
const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(c/100);
const pct=(n:number)=>`${Math.round(n*100)}%`;
const monthLabel=(m:string)=>new Date(`${m}-02T12:00:00`).toLocaleDateString("en-US",{month:"short",year:"2-digit"});

function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[];let cell="";let q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(q&&text[i+1]==='"'){cell+='"';i++;}else q=!q;}else if(ch===","&&!q){row.push(cell);cell="";}else if((ch==="\n"||ch==="\r")&&!q){if(ch==="\r"&&text[i+1]==="\n")i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell="";}else cell+=ch;}if(cell||row.length){row.push(cell);rows.push(row);}const headers=(rows.shift()||[]).map(x=>x.trim());return{headers,rows:rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??""])))}} 

export default function Financials(){
 const[mode,setMode]=useState("checking"),[homes,setHomes]=useState<Home[]>([]),[tx,setTx]=useState<Tx[]>([]),[view,setView]=useState<View>("overview");
 const[filter,setFilter]=useState<"all"|"review"|"matched"|"overhead">("all"),[selected,setSelected]=useState<string[]>([]),[selectedHome,setSelectedHome]=useState("");
 const[period,setPeriod]=useState<"all"|"3"|"6"|"12">("all");
 const[showImport,setShowImport]=useState(false),[fileName,setFileName]=useState(""),[headers,setHeaders]=useState<string[]>([]),[rows,setRows]=useState<Record<string,string>[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const[mapping,setMapping]=useState<Record<string,string>>({date:"",description:"",vendor:"",amount:"",debit:"",credit:"",account:"",qbClass:"",qbLocation:"",customerProject:"",memo:"",positiveMeans:"expense"});
 async function load(){const r=await fetch("/api/financial/bootstrap"),b=await r.json();if(r.status===401){setMode("auth");return}if(!r.ok){setMode("error");setMsg(b.error||"Could not load financials");return}setMode(b.mode);setHomes(b.homes||[]);setTx(b.transactions||[]);setSelectedHome(x=>x||b.homes?.[0]?.id||"")}
 useEffect(()=>{load()},[]);
 const periodTx=useMemo(()=>{if(period==="all"||!tx.length)return tx;const latest=tx.reduce((max,row)=>row.tx_date>max?row.tx_date:max,tx[0].tx_date),cutoff=new Date(`${latest}T12:00:00`);cutoff.setMonth(cutoff.getMonth()-Number(period)+1);const key=cutoff.toISOString().slice(0,7);return tx.filter(row=>row.tx_date.slice(0,7)>=key)},[tx,period]);
 const intel=useMemo(()=>buildPortfolioIntelligence(homes,periodTx),[homes,periodTx]),visible=useMemo(()=>filter==="all"?tx:tx.filter(t=>t.allocation_status===filter),[tx,filter]),property=intel.properties.find(x=>x.home.id===selectedHome)||intel.properties[0],maxMonth=Math.max(1,...intel.months.flatMap(m=>[m.revenue,m.expenses]));
 async function assign(id:string,propertyId:string|null,overhead=false){if(mode!=="live"){setTx(xs=>xs.map(t=>t.id===id?{...t,allocation_status:overhead?"overhead":propertyId?"matched":"review",property_id:propertyId,homes:homes.find(h=>h.id===propertyId)||null,match_confidence:propertyId||overhead?1:0}:t));return}const r=await fetch(`/api/financial/transactions/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(overhead?{markOverhead:true}:{propertyId})});if(r.ok){const b=await r.json();setTx(xs=>xs.map(t=>t.id===id?b.transaction:t))}}
 async function bulk(propertyId?:string,overhead=false){if(!selected.length)return;if(mode!=="live"){for(const id of selected)await assign(id,propertyId||null,overhead);setSelected([]);return}setBusy(true);const r=await fetch("/api/financial/bulk-review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids:selected,propertyId,markOverhead:overhead})});setBusy(false);if(r.ok){setSelected([]);load()}}
 function chooseFile(file?:File){if(!file)return;setFileName(file.name);file.text().then(text=>{const p=parseCsv(text);setHeaders(p.headers);setRows(p.rows);const find=(...ns:string[])=>p.headers.find(h=>ns.some(n=>h.toLowerCase().includes(n)))||"";setMapping(m=>({...m,date:find("date"),description:find("description","name"),vendor:find("vendor","payee"),amount:find("amount"),debit:find("debit"),credit:find("credit"),account:find("account"),qbClass:find("class"),qbLocation:find("location"),customerProject:find("customer","project"),memo:find("memo")}))})}
 async function importRows(){if(!mapping.date||(!mapping.amount&&!mapping.debit&&!mapping.credit)){setMsg("Map a date and either amount or debit/credit columns first.");return}if(mode!=="live"){setMsg("Import mapping is ready. Connect Supabase to persist the QuickBooks export.");return}setBusy(true);const r=await fetch("/api/financial/imports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fileName,mapping,rows})}),b=await r.json();setBusy(false);if(!r.ok){setMsg(b.error||"Import failed");return}setMsg(`Imported ${b.total} rows: ${b.matched} auto-matched, ${b.review} need review.`);setShowImport(false);load()}
 const tabs:{id:View;label:string}[]=[{id:"overview",label:"Portfolio overview"},{id:"properties",label:"Property P&L"},{id:"services",label:"Vendors & services"},{id:"trends",label:"Trends & gaps"},{id:"review",label:`Review queue${intel.review?` (${intel.review})`:""}`}];
 return <main className="finShell"><aside className="finSide"><BrandLockup href="/" className="finBrand" /><nav><a className="finNav" href="/"><BrandIcon name="listing" className="navIcon" />Operations</a><a className="finNav active" href="/financials"><BrandIcon name="rent" className="navIcon" />Portfolio Intel</a><a className="finNav" href="/vendors"><BrandIcon name="applications" className="navIcon" />Approved Vendors</a></nav><div className="portfolio"><small>CONTROLLER VIEW</small><strong>{homes.length} doors</strong><span>{intel.review} items need review</span><span className={`mode ${mode}`}>{mode==="live"?"● Live accounting data":mode==="demo"?"○ Demo financial data":`Backend status: ${mode}`}</span></div></aside>
 <section className="finContent"><header className="finHeader"><div><p className="eyebrow">PORTFOLIO INTELLIGENCE</p><h1>See where every property earns—and leaks</h1><p>Compare property profitability, service costs, vendor concentration, trends, and accounting gaps from one controller view.</p></div><div className="headerActions"><select className="periodSelect" value={period} onChange={e=>setPeriod(e.target.value as typeof period)}><option value="all">All imported data</option><option value="3">Last 3 months</option><option value="6">Last 6 months</option><option value="12">Last 12 months</option></select>{mode==="auth"&&<a className="secondaryBtn" href="/login">Sign in</a>}<button className="primary" onClick={()=>setShowImport(true)}>Import QuickBooks export</button></div></header>{msg&&<div className="backendBanner">{msg}</div>}<div className="intelTabs">{tabs.map(t=><button key={t.id} className={view===t.id?"active":""} onClick={()=>setView(t.id)}>{t.label}</button>)}</div>
 {view==="overview"&&<><MetricCards intel={intel}/><div className="intelGrid"><div className="panel"><PanelTitle eyebrow="ACTION CENTER" title="What needs attention" aside={<span className="pill">Rules-based</span>}/><InsightList insights={intel.insights}/></div><div className="panel"><PanelTitle eyebrow="COST MIX" title="Expense by service type" aside={<button className="textBtn" onClick={()=>setView("services")}>View vendors →</button>}/><div className="barList">{intel.categories.slice(0,6).map(c=><div className="barRow" key={c.name}><div><strong>{c.name}</strong><span>{c.transactions} transactions · {c.properties} properties</span></div><div className="barTrack"><i style={{width:`${Math.max(3,c.share*100)}%`}}/></div><b>{money(c.spend)}</b></div>)}</div></div></div><div className="panel"><PanelTitle eyebrow="DOOR RANKING" title="Property profitability" aside={<button className="textBtn" onClick={()=>setView("properties")}>Open property P&Ls →</button>}/><PropertyTable properties={intel.properties} onSelect={id=>{setSelectedHome(id);setView("properties")}}/></div></>}
 {view==="properties"&&<><div className="propertyPicker"><div><p className="eyebrow">PROPERTY DETAIL</p><h2>Individual property P&L</h2></div><select value={property?.home.id||""} onChange={e=>setSelectedHome(e.target.value)}>{intel.properties.map(x=><option key={x.home.id} value={x.home.id}>{x.home.address1}</option>)}</select></div>{property&&<><div className="stats finStats"><div className="stat"><span>Revenue</span><div className="statValue good">{money(property.revenue)}</div></div><div className="stat"><span>Expenses</span><div className="statValue">{money(property.expenses)}</div><small>{property.revenue?pct(property.expenses/property.revenue):"No income mapped"}</small></div><div className="stat"><span>NOI</span><div className={`statValue ${property.noi>=0?"good":"warn"}`}>{money(property.noi)}</div></div><div className="stat"><span>NOI margin</span><div className="statValue">{pct(property.margin)}</div><small>{property.serviceTypes} service types</small></div></div><div className="intelGrid"><div className="panel"><PanelTitle eyebrow="PROFIT & LOSS" title={property.home.address1} aside={<span className={`health ${property.noi>=0?"good":"urgent"}`}>{property.noi>=0?"Profitable":"Operating loss"}</span>}/><div className="pnl"><div><span>Rental and other income</span><strong>{money(property.revenue)}</strong></div>{[...new Set(property.rows.filter(r=>r.flow_type==="expense").map(r=>r.account_name||"Uncategorized"))].map(cat=>{const spend=property.rows.filter(r=>r.flow_type==="expense"&&(r.account_name||"Uncategorized")===cat).reduce((s,r)=>s+r.amount_cents,0);return <div key={cat}><span>{cat}</span><strong>−{money(spend)}</strong></div>})}<div className="total"><span>Net operating income</span><strong>{money(property.noi)}</strong></div></div></div><div className="panel"><PanelTitle eyebrow="LEDGER DETAIL" title="Mapped transactions" aside={<span className="pill">{property.rows.length} rows</span>}/><div className="compactLedger">{property.rows.toSorted((a,b)=>b.tx_date.localeCompare(a.tx_date)).map(r=><div key={r.id}><span><strong>{r.vendor_name||r.description||"Transaction"}</strong><small>{r.tx_date} · {r.account_name||"Uncategorized"}</small></span><b className={r.flow_type}>{r.flow_type==="income"?"+":"−"}{money(r.amount_cents)}</b></div>)}</div></div></div><div className="panel"><PanelTitle eyebrow="PORTFOLIO BENCHMARK" title="All properties"/><PropertyTable properties={intel.properties} onSelect={setSelectedHome}/></div></>}</>}
 {view==="services"&&<div className="intelGrid"><div className="panel"><PanelTitle eyebrow="SERVICE-TYPE ANALYSIS" title="Where the portfolio spends"/><div className="serviceTable"><div className="serviceTr head"><span>Service type</span><span>Class</span><span>Spend</span><span>Avg invoice</span><span>Properties</span></div>{intel.categories.map(c=><div className="serviceTr" key={c.name}><span><strong>{c.name}</strong><small>{c.transactions} transactions · {pct(c.share)} of spend</small></span><span><b className={`costClass ${c.expenseClass.toLowerCase()}`}>{c.expenseClass}</b></span><span>{money(c.spend)}</span><span>{money(c.averageInvoice)}</span><span>{c.properties}</span></div>)}</div></div><div className="panel"><PanelTitle eyebrow="CONCENTRATION" title="Vendor exposure" aside={<span className="pill">Top spend first</span>}/><div className="vendorCards">{intel.vendors.map(v=><div className="vendorCard" key={v.name}><div><strong>{v.name}</strong><span>{v.categories.join(" · ")}</span></div><b>{money(v.spend)}</b><div className="vendorMeta"><span>{pct(v.share)} of spend</span><span>{v.properties} properties</span><span>{money(v.average)} avg ticket</span></div></div>)}</div></div></div>}
 {view==="trends"&&<><div className="panel"><PanelTitle eyebrow="MONTHLY PERFORMANCE" title="Revenue, expenses, and NOI trend" aside={<span className="pill">Imported months</span>}/><div className="trendChart">{intel.months.map(m=><div className="trendMonth" key={m.month}><div className="trendBars"><i className="revenueBar" style={{height:`${Math.max(3,m.revenue/maxMonth*100)}%`}}/><i className="expenseBar" style={{height:`${Math.max(3,m.expenses/maxMonth*100)}%`}}/></div><strong>{monthLabel(m.month)}</strong><span className={m.noi>=0?"goodText":"badText"}>{money(m.noi)} NOI</span></div>)}</div><div className="chartLegend"><span><i className="revenueKey"/>Revenue</span><span><i className="expenseKey"/>Expenses</span></div></div><div className="intelGrid"><div className="panel"><PanelTitle eyebrow="GAP ANALYSIS" title="Data and performance gaps"/><InsightList insights={intel.insights}/></div><div className="panel"><PanelTitle eyebrow="MONTHLY P&L" title="Period comparison"/><div className="monthlyTable">{intel.months.map(m=><div key={m.month}><strong>{monthLabel(m.month)}</strong><span>{money(m.revenue)} revenue</span><span>{money(m.expenses)} expense</span><b className={m.noi>=0?"goodText":"badText"}>{money(m.noi)}</b></div>)}</div></div></div></>}
 {view==="review"&&<div className="panel"><div className="panelHead"><div><p className="eyebrow">DATA QUALITY</p><h2>Transaction review queue</h2></div><div className="finFilters">{(["all","review","matched","overhead"] as const).map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}</button>)}</div></div>{selected.length>0&&<div className="bulkBar"><strong>{selected.length} selected</strong><select defaultValue="" onChange={e=>{if(e.target.value)bulk(e.target.value)}}><option value="">Assign all to property…</option>{homes.map(h=><option key={h.id} value={h.id}>{h.address1}</option>)}</select><button onClick={()=>bulk(undefined,true)} disabled={busy}>Mark company overhead</button></div>}<div className="finTable"><div className="finTr finHead"><span/><span>Date / vendor</span><span>Account</span><span>Amount</span><span>Property assignment</span><span>Confidence</span></div>{visible.map(t=><div className="finTr" key={t.id}><span><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,t.id]:s.filter(x=>x!==t.id))}/></span><span><strong>{t.vendor_name||t.description||"Transaction"}</strong><small>{t.tx_date} · {t.description}</small></span><span>{t.account_name||"Uncategorized"}</span><span className={t.flow_type}>{t.flow_type==="income"?"+":"−"}{money(t.amount_cents)}</span><span><select value={t.allocation_status==="overhead"?"overhead":t.homes?.id||t.property_id||""} onChange={e=>e.target.value==="overhead"?assign(t.id,null,true):assign(t.id,e.target.value||null)}><option value="">Needs review</option><option value="overhead">Company overhead</option>{homes.map(h=><option key={h.id} value={h.id}>{h.address1}</option>)}</select></span><span><b className={`confidence ${t.match_confidence>=.9?"high":t.match_confidence>.5?"medium":"low"}`}>{Math.round((t.match_confidence||0)*100)}%</b></span></div>)}</div></div>}
 </section>
 {showImport&&<div className="modalShade"><div className="modal importModal"><div className="modalHead"><div><p className="eyebrow">QUICKBOOKS IMPORT</p><h2>Map your export once</h2></div><button className="closeBtn" onClick={()=>setShowImport(false)}>×</button></div><p className="summary">Map however properties appear in QuickBooks; unmatched rows go to the controller review queue.</p><label className="dropZone">Choose QuickBooks CSV<input type="file" accept=".csv,text/csv" onChange={e=>chooseFile(e.target.files?.[0])}/><strong>{fileName||"Choose CSV file"}</strong><span>{rows.length?`${rows.length} transactions detected`:"Export a report from QuickBooks Online as CSV-compatible data"}</span></label>{headers.length>0&&<div className="mappingGrid">{[["date","Transaction date *"],["vendor","Vendor / payee"],["description","Description"],["amount","Amount"],["debit","Debit"],["credit","Credit"],["account","Account / category"],["qbClass","QuickBooks Class"],["qbLocation","QuickBooks Location"],["customerProject","Customer / Project"],["memo","Memo"]].map(([key,label])=><label key={key}>{label}<select value={mapping[key]||""} onChange={e=>setMapping({...mapping,[key]:e.target.value})}><option value="">Not mapped</option>{headers.map(h=><option key={h} value={h}>{h}</option>)}</select></label>)}</div>}<div className="modalActions"><button className="secondaryBtn" onClick={()=>setShowImport(false)}>Cancel</button><button className="primary" onClick={importRows} disabled={busy||!rows.length}>{busy?"Importing…":"Import & auto-match"}</button></div></div></div>}
 </main>
}

function PanelTitle({eyebrow,title,aside}:{eyebrow:string;title:string;aside?:React.ReactNode}){return <div className="panelHead"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{aside}</div>}
function MetricCards({intel}:{intel:ReturnType<typeof buildPortfolioIntelligence>}){return <div className="stats finStats"><div className="stat"><span>Portfolio revenue</span><div className="statValue good">{money(intel.revenue)}</div><small>Selected period</small></div><div className="stat"><span>Operating expenses</span><div className="statValue">{money(intel.operatingExpenses)}</div><small>{pct(intel.operatingExpenses/(intel.revenue||1))} of revenue</small></div><div className="stat"><span>Operating NOI</span><div className={`statValue ${intel.operatingNoi>=0?"good":"warn"}`}>{money(intel.operatingNoi)}</div><small>Excludes capital improvements</small></div><div className="stat"><span>Capital improvements</span><div className="statValue">{money(intel.capitalExpenses)}</div><small>{money(intel.overhead)} company overhead</small></div></div>}
function InsightList({insights}:{insights:ReturnType<typeof buildPortfolioIntelligence>["insights"]}){return <div className="insightList">{insights.map((x,i)=><div key={x.title+i} className={`insight ${x.severity}`}><span/><div><strong>{x.title}</strong><p>{x.detail}</p></div></div>)}</div>}
function PropertyTable({properties,onSelect}:{properties:ReturnType<typeof buildPortfolioIntelligence>["properties"];onSelect:(id:string)=>void}){return <div className="portfolioTable"><div className="portfolioTr intelHead"><span>Property</span><span>Revenue</span><span>Expenses</span><span>NOI</span><span>Margin</span></div>{properties.map(x=><button className="portfolioTr propertyLink" key={x.home.id} onClick={()=>onSelect(x.home.id)}><span><strong>{x.home.address1}</strong><small>{x.home.city}, {x.home.state}</small></span><span>{money(x.revenue)}</span><span>{money(x.expenses)}</span><span className={x.noi>=0?"goodText":"badText"}><strong>{money(x.noi)}</strong></span><span>{pct(x.margin)} →</span></button>)}</div>}
